### PR TITLE
Adding Facebook status-message comments (and the new-comment form).

### PR DESCRIPTION
**Pull request by jmacdotorg**
This may seem a bit silly! But honestly, often when I visit Facebook it's because I wish to see my friends' status messages; all the additional commentary from their random high school friends and their politically passionate uncles and so forth are not always welcome. And so, this is my proposed addition.

### CODE REVIEW

**Comment by RickyRomero** [comment]
Just noticed this conversation.

There are a few sites like this – Github, Reddit, Facebook, StackOverflow – which are arguably more useful with comments than without...  And then there's the false-positive sites.

With the extension, if a user toggles the comments on, it could potentially act as a vote to always show them.  With enough votes, we could show the comments on that site by default for all users (and then, hiding them again could act as a vote against).  But, there are definitely privacy concerns to think about when dealing with this kind of information...

**Comment by RickyRomero** [comment]
We should be able to close this - comments are blocked on Facebook in the latest stylesheet.

**Comment by panicsteve** [comment]
Closing, per Ricky

**Comment by jmacdotorg** [comment]
Super duper. Thanks y'all.

**Pull request closed without merging**
